### PR TITLE
feat(config): add envFile option

### PR DESCRIPTION
**Pull request by c4spar**
This add's a new option `env_file` to the scripts config.

The feature is described in the documentation: https://github.com/c4spar/velociraptor/tree/feature/env_file#environment-variables.

Test's are also updated.

### CODE REVIEW

**Comment by c4spar** [comment]
Ready for review 😉

If you want, i can also replace the readFileSync with an readFile call to make it asyncronous. But this requries more changes.

**Comment by umbopepato** [comment]
Hey @c4spar, thank you so much for the PR!
I like the idea of supporting external env files, just a few points:

- All other multi-word script object params are `camelCase` so I guess it would make sense to name it `envFile`, what do you say?
- Do you think it would make sense to accept both `string` and `string[]`? Like
  ```yaml
  scripts:
    start:
      envFile: .env
      # and
      envFile:
        - .env
        - .env.production
  ```

**Comment by c4spar** [comment]
Sry my bad, i fixed the option naming and i have also changed the type to `string | string[]`.

**Comment by umbopepato** [comment]
Awesome, thank you so much @c4spar! 🙌

**Pull request merged**
